In [ ]:
#import the data set
from sklearn.datasets import load_iris
import numpy as np
from sklearn import tree


In [ ]:
iris = load_iris()

In [ ]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [ ]:
print(iris.data[0])

[5.1 3.5 1.4 0.2]


In [ ]:
print(iris.data[1])

[4.9 3.  1.4 0.2]


In [ ]:
print(iris.target[0])

0


In [ ]:
for i in range(52):
  print('features :',iris.data[i])
  print('the target flower :',iris.target_names[iris.target[i]],'\n')

features : [5.1 3.5 1.4 0.2]
the target flower : setosa 

features : [4.9 3.  1.4 0.2]
the target flower : setosa 

features : [4.7 3.2 1.3 0.2]
the target flower : setosa 

features : [4.6 3.1 1.5 0.2]
the target flower : setosa 

features : [5.  3.6 1.4 0.2]
the target flower : setosa 

features : [5.4 3.9 1.7 0.4]
the target flower : setosa 

features : [4.6 3.4 1.4 0.3]
the target flower : setosa 

features : [5.  3.4 1.5 0.2]
the target flower : setosa 

features : [4.4 2.9 1.4 0.2]
the target flower : setosa 

features : [4.9 3.1 1.5 0.1]
the target flower : setosa 

features : [5.4 3.7 1.5 0.2]
the target flower : setosa 

features : [4.8 3.4 1.6 0.2]
the target flower : setosa 

features : [4.8 3.  1.4 0.1]
the target flower : setosa 

features : [4.3 3.  1.1 0.1]
the target flower : setosa 

features : [5.8 4.  1.2 0.2]
the target flower : setosa 

features : [5.7 4.4 1.5 0.4]
the target flower : setosa 

features : [5.4 3.9 1.3 0.4]
the target flower : setosa 

features : [5.

In [ ]:
# lets take the first params from the data set for each flower
test = [0,50,100]


In [ ]:
# lets train the data
train_target = np.delete(iris.target, test)
train_data = np.delete(iris.data, test, axis=0)
test_target = iris.target[test]
test_data = iris.data[test]
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
print(test_data)

[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]]


In [ ]:
print(clf.predict(test_data))

[0 1 2]
